### ISSUE TITLE
parameter number inconsistency with \landi and e.g. \lfalsei

### ISSUE THREAD

**Issue by f0rki** [rzach/lplfitch#1]
Hi,

So I noticed that `\landi` takes only one parameter and for example `\lfalsei` takes two parameters. But usually I supply both with two line numbers. So I'd have to go with `\landi{2, 3}` and `\lfalsei{2}{3}`, which is kind of inconsistent and confusing.
Is there a reason for this or is it just a "bug"?

thx and cheers

**Comment by rzach** [comment]
It's on purpose since \landi can take more than 2 premises.
